version: "3"

services:
  db:
    container_name: blog_db_dev
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: "5up3r53cr37!"
      POSTGRES_DB: "blog_dev"
    ports:
    - "5432:5432"
    volumes:
    - ./db/postgres-dev:/var/lib/postgresql
