name: Pre-release

on:
  pull_request:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - run: npm ci
      - name: Set application version
        run: echo "BLOG_APPLICATION_VERSION=v$(npm pkg get version | xargs)" >> $GITHUB_ENV
      - run: npm run build
      - run: npm test
      - name: Create release assets
        run: |
          tar -czvf build.tgz -C build .
      - name: Publish release on GitHub
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create $BLOG_APPLICATION_VERSION ./*.tgz --generate-notes --prerelease
